on:
  push:
    branches:
      - main
      - development

jobs:
  create_arch_images:
    runs-on: ubuntu-latest
    name: An automated way to create the image
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create the img
        uses: ./
        id: create
        with: 
          file: 'diagram.py'
      - name: Get the opt
        run: echo "the time was ${{ steps.create.outputs.files }}"
      - name: list files
        run: ls
