on:
  push:
    branches:
      - CI-Development
      - main

jobs:
  create_arch_images:
    runs-on: ubuntu-latest

    name: Take care of the repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create the docker image
        run: DOCKER_BUILDKIT=1 docker build --file Dockerfile --output out . 
      
      - name: share the compiled files
        uses: actions/upload-artifact@v3
        with:
          name: files
          path: out/


